title = "Configuration file for the policies"

# Optimal Reciprocal Collision Avoidance
[orca]
neighbor_dist = 20
max_neighbors = 10
time_horizon = 6
time_horizon_obst = 10
radius = 0.3

# Inverse of ORCA for the robot
[inverse_orca]
time_horizon = 6
radius = 0.3
collision_responsibility = 1.0
orca_time_horizon = 6
neighbor_dist = 20
max_neighbors = 10
orca_time_horizon_obst = 10

# Weighted sum policy for the robot
[weighted_sum]
goal_weight = 0.5

# The configuration for the social force model
[scene]
enable_group = false
agent_radius = 0.3
# the maximum speed doesn't exceed 1.0x initial speed
max_speed_multiplier = 1.0
step_width = 0.25

[desired_force]
factor = 1.0
# The relaxation distance of the goal
goal_threshold = 0.0
# How long the relaxation process would take
relaxation_time = 0.5

[social_force]
factor = 5.1
# Moussaid-Helbing 2009
# relative importance of position vs velocity vector
lambda_importance = 2.0
# define speed interaction
gamma = 0.35
n = 2
# define angular interaction
n_prime = 3

[obstacle_force]
factor = 10.0
# the standard deviation of obstacle force
sigma = 0.2
# threshold to trigger this force
threshold = 3.0

[group_coherence_force]
factor = 3.0

[group_repulsive_force]
factor = 1.0
# threshold to trigger this force
threshold = 0.55

[group_gaze_force]
factor = 4.0
# fielf of view
fov_phi = 90.0
