title = "Configuration file for simulation settings"

# Simumlation settings
num_runs = 50
save_anim = false
render_mode = 'human'
robot_policy = 'inverse_orca'
human_policy = 'orca'
out_fname = 'temp'
save_data = false
print_summary = false