title = "Configuration file for simulation settings"

# Simumlation settings
num_runs = 1
save_anim = true
render_mode = 'human'
robot_policy = 'weighted_sum'
human_policy = 'social_force'
out_fname = 'temp'
save_data = true
print_summary = false