title = "Configuration file for simulation settings"

# Simumlation settings
num_runs = 1
save_anim = true
render_mode = 'debug'
robot_policy = 'inverse_orca'
human_policy = 'orca'
out_fname = 'temp'
save_data = true
print_summary = false