title = "Configuration file for simulation settings"

# Simumlation settings
num_runs = 1
save_anim = true
render_mode = 'human'
robot_policy = 'efficient_nudge'
human_policy = 'orca'
out_fname = 'temp'
save_data = false
print_summary = false